#! /bin/bash

keys2lines() {
    python -c "exec(\" \
        \nimport json as j \
        \nimport sys  as s \
        \nfor key in j.loads(s.stdin.read())['keys']: \
        \n  print key \
    \")"
}

main() {
    repo_path=$1
    hostname=$2
    bucket=$3
    port=8098
    mkdir -p $repo_path/$bucket
    cd $repo_path
    git init
    keys=$(
        curl -i http://$hostname:$port/riak/$bucket\?keys\=true 2> /dev/null \
        | tail -1 \
        | keys2lines
    )
    for key in $keys;
    do
        curl -i http://$hostname:$port/riak/$bucket/$key 2> /dev/null \
        | tail -1 \
        > $bucket/$key
        git add . && git commit -m "Update $bucket/$key"
    done
}

main $@
